name: performance_record
channels:
  - conda-forge
dependencies:
  # Python 3.8 is the final Python series that supports Windows 7.
  - python=3.8.20
  - pyqt=5.15.9
  - qt-main=5.15.8
  - matplotlib=3.7.3
  - numpy=1.24.4
  - pip
  - pip:
      - pyinstaller==6.17.0
